#ifndef GAME_H
#define GAME_H

#include "types.h"

/*-------------------Functions--------------------*/
void memcpy(void* dst, void* src, int size);
void memset(void* destination, char val, int size);
void printf(char* fmt, ...);
void sprintf(char* dst, char* fmt, ...);

void text_medium_left(int x, int y, uint32_t colour, char* text, int max_length);
void text_medium_center(int x, int y, uint32_t colour, char* text, int max_length);
void text_medium_right(int x, int y, uint32_t colour, char* text, int max_length);
void text_small_right(int x, int y, uint32_t colour, char* text, int max_length);
void text_small_center(int x, int y, uint32_t colour, char* text, int max_length);
void text_small_left(int x, int y, uint32_t colour, char* text, int max_length);
void text_large_center(int x, int y, uint32_t colour, char* text, int max_length);
void text_large_as_fuck(int x, int y, uint32_t colour, char* text, int max_length);
void draw_box(int x1, int y1, int x2, int y2, int colour, char flags);
void toast_message(char* text, int length);

void syscall(int syscall_num, ...);




// Since we're compiling with -m32, the stack frames that get generated by the
// compiler are way smaller than what the game expects a function calling stuff
// to be. For functions that use sprintf, we have to allocate space on the stack 
// to avoid stack buffer overflow from overwriting the return address.
#define reserve_stack(size) \
    volatile char temp[size]; \
    temp[0] = 0;


/*-------------------Globals--------------------*/

extern Moby* moby_instance_table;
extern Moby* moby_instance_perm_end;
extern Moby* moby_instance_end;

extern int frames_since_spawn;
extern int frames_since_reload;
extern int death_count;
extern GameState gamestate;
extern int player_state;
extern Vec4 player_coords;
extern int current_weapon;
extern float neutral_speed;
extern int should_load;
extern planetId destination_planet;

extern planetId current_planet;

#endif