player_moby        = 0x96BD60;
down_buttons       = 0x964AE0;
current_planet     = 0x969C70;
should_load        = 0xA10700;
destination_planet = 0xA10704;
ui_screen          = 0xA10708;
time_since_reload  = 0xA10710;
savedata_base      = 0xA10928;
moby_first         = 0xA390A0;
moby_last          = 0xA390A8;
class_index        = 0xA354C0;
class_table        = 0xA34C00;

gcm_ctx            = 0x8FA43C;
hud_textures       = 0xA15F68;
font_info          = 0xA1A7A0;
glyphs             = 0x7368B0;
rs_blend           = 0x10EE318;
rs_filter          = 0x10EE2F0;
camera_pos         = 0x951500;
world_to_screen    = 0x951440;

fn_spawn_moby              = 0xEFA28;
fn_perform_load            = 0xE8CA0;
fn_memcpy                  = 0x5C5AD0;
fn_draw_center_medium_text = 0x70514;
fn_hud_debug_panel         = 0x7C978;
